---
version: "2"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM=   # claim code from https://www.plex.tv/claim/
      - ADVERTISE_IP=http://192.168.1.177:32400/
    hostname: plexserver
    volumes:
      - /Configs/plex/database:/config
      - /Configs/plex/transcode:/transcode
      - /Configs/plex/media:/data
      - /Storage/TV:/TV
      - /Storage/Movies:/Movies
      - /Storage/Music:/Music

    
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=000 
      - TZ=Europe/London
    volumes:
      - /Configs/Jackett:/config
      - /Storage/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=000 
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24 #adjust this to YOUR network settings
      - NAME_SERVERS=8.8.8.8,1.1.1.1 #you can use whatever DNS provider you want
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - /Configs/QBittorrentVPN:/config
      - /Storage/Torrents:/downloads
      - /etc/timezone:/etc/timezone:ro #This is for TimeZone
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=000 
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /Configs/Radarr:/config
      - /Storage/Movies:/movies
      - /Storage/Torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
        
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - UMASK=000 
    volumes:
      - /Configs/Sonarr:/config
      - /Storage/TV:/tv
      - /Storage/Torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=000 
      - TZ=Etc/UTC
    volumes:
      - /Configs/lidarr:/config
      - /Storage/Music:/music 
      - /Storage/Torrents:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-32769}:8191"
    restart: unless-stopped 
